### ISSUE TITLE
Moving views with the keyboard

### ISSUE THREAD

**Issue by timothy1ee** [codepath/ios_guides#11]
There's already a guide for keyboard events - http://guides.codepath.com/ios/Registering-for-Keyboard-Events. Add a use case guide for moving some textfields with keyboard appearance/disappearance.

**Comment by timothy1ee** [comment]
Note that in iOS, there's a little autocomplete view on top of the keyboard. Every time you show or hide the autocomplete view, it will call keyboardWillHide and keyboardWillShow multiple times even though the keyboard isn't actually disappearing.

Therefore, you can't increment or decrement y values. Instead, you have to set it to fixed up and down positions.

**Comment by tonysherbondy** [comment]
I don't think this is a situation where we need to add a use case. The basic use case is actually trying to demonstrate that behavior. I just think we need to add a last step where we modify other views in the event handler.

**Comment by tonysherbondy** [comment]
http://guides.codepath.com/ios/Registering-for-Keyboard-Events is ready for review.

**Comment by ericcgu** [comment]
May be a good move to remove observers in viewWillDisappear.
