### ISSUE TITLE
Color matching via the color picker

### ISSUE THREAD

**Issue by timothy1ee** [codepath/ios_guides#12]
Sometimes you have an image asset that has some background color. Let's say you want to set the background color of some view to match the color of the asset. If you use the dropper in the color picker, the color won't match.

Can you find the solution for this for Mavericks (I think it's different for earlier versions of OS X) and create a guide for it?

**Comment by tonysherbondy** [comment]
So, the best method I have is:
1. Select color picker
2. Point and shoot at image color you would like to match
3. Make note of the RGB numbers on the screen.
4. (Unfortunately, the color picker always puts your color mode in "Device RGB") You need to pick the color mode dropdown and change the mode to "Generic RGB".
5. Copy the RGB numbers from the previous mode into the RGB text boxes.

See the gif here
(http://imgur.com/VkEin5S)
