### ISSUE TITLE
Better Designer Guide Organization

### ISSUE THREAD

**Issue by tonysherbondy** [codepath/ios_guides#16]
From Tim -> in the designer guides, can you create another category for “Views”. There are things that are in "Animating and Responding to User Input” that should probably be moved to the “Views” category. Also, “UIKit Dynamics” doesn’t seem to belong in “Common Views and Controllers"

**Comment by tonysherbondy** [comment]
@timothy1ee Took another pass. Please review again.

**Comment by nickai** [comment]
Closing this out.
