### ISSUE TITLE
readme template for each HW

### ISSUE THREAD

**Issue by tonysherbondy** [codepath/ios_guides#17]
Adjust this template for each designer assignment.
https://github.com/codepath/ios_guides/wiki/Readme-Template-iOS-for-Designers-Week-1

**Comment by tonysherbondy** [comment]
@timothy1ee weeks 1-3 are ready for review
https://github.com/codepath/ios_guides/wiki/Readme-Template-iOS-for-Designers-Week-1
https://github.com/codepath/ios_guides/wiki/Readme-Template-iOS-for-Designers-Week-2
https://github.com/codepath/ios_guides/wiki/Readme-Template-iOS-for-Designers-Week-3

**Comment by nickai** [comment]
Closing out this old issue. The readme templates should probably go in the courses_content repo in the future.
