### ISSUE TITLE
Table View Guide UIRefreshControl 

### ISSUE THREAD

**Issue by modu** [codepath/ios_guides#23]
func refreshControlAction(refreshControl: UIRefreshControlAction) {
should be 
func refreshControlAction(refreshControl: UIRefreshControl) {
As I was getting with UIRefreshControlAction so changed it to UIRefreshControl. It worked.

**Comment by chieger** [comment]
Thanks Varun!

I will look into this.

Charlie

**Comment by nickai** [comment]
Forgot to close out the issue (fixed the guide last night).

-Nick
