### ISSUE TITLE
Multithreading Guide

### ISSUE THREAD

**Issue by nickai** [codepath/ios_guides#24]
Placeholder: http://guides.codepath.com/ios/Multithreading-in-iOS

**Comment by Jasdev** [comment]
@nickai Just added a high-level outline, how's it look?

https://github.com/codepath/ios_guides/wiki/Multithreading-in-iOS

**Comment by nickai** [comment]
Looks great! A couple of thoughts:
* Might be good to have an "Overview" section that briefly captures what multithreading is and why it is needed
* What do you think of also including a short section on [performSelectorInBackground](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/#//apple_ref/occ/instm/NSObject/performSelectorInBackground:withObject:) - just to show that it exists
* It would be nice to use the as much of the same example across both GCD and NSOperation as possible (which it looks like you are planning to do). I think this would make the differences between the 2 options stand out more.
* If you've got a cool Swift wrapper around GCD that might be the type of thing that we can create a gist for and link to it (depending on how extensive it is)

**Comment by nickai** [comment]
@Jasdev - How's it going with this guide?

**Comment by Jasdev** [comment]
@nickai Still working on it! Sorry, this weekend I had friends visiting, so I wasn't able to make as much progress as I wanted :/ I'll have bandwidth tomorrow and Thursday evening to tackle this!

**Comment by nickai** [comment]
Sounds good...thanks!

**Comment by Jasdev** [comment]
@nickai Added the guide! Please let me know of (or feel free to make any) edits!

**Comment by nickai** [comment]
@Jasdev - Looks really good! 

I updated the section headings so that the section outline kicks in.

One suggestion I have is to move the descriptions of the code blocks (listed as bullets below the code) into inline comments in the code. This tends to make the code easier to digest.

Thanks so much for your help! I'm really happy we have a multithreading guide now!
