### ISSUE TITLE
Optionally Add Formatting to Code Snippets

### ISSUE THREAD

**Issue by ericcgu** [codepath/ios_guides#3]
If you add Language (Swift) to tickmarks in Code Snippet Markup, color formatting with ensue: (see below)

![screen shot 2015-03-12 at 2 29 19 pm](https://cloud.githubusercontent.com/assets/4943759/6625148/7f6a3ea0-c8c4-11e4-83e5-ec1e95652bf5.png)

![screen shot 2015-03-12 at 2 30 23 pm](https://cloud.githubusercontent.com/assets/4943759/6625144/7c6be1cc-c8c4-11e4-8ae9-273a455e06e1.png)

**Comment by nickai** [comment]
:+1: Good tip. I've added this to the [contributing guidelines](http://guides.codepath.com/ios/Contributing-Guidelines) and updated a bunch of the guides that don't have code formatting.
