### ISSUE TITLE
Parse Guide Enhancements

### ISSUE THREAD

**Issue by nickai** [codepath/ios_guides#38]
**Completed**:
- [x] Downloading an image from Parse and displaying in an PFImageView
- [x] Add a section on explaining how to add keys
- [x] Refactor getting started to put less emphasis on Parse.com and talk about both options (Parse.com vs Parse Server)
- [x] UserMedia renamed to Post
- [x] Link to Cocoa Pods and Swift Guide (Trim explanations in guide)
- [x] Remove screenshots of code
- [x] [Setting up your own Parse dashboard](http://blog.parse.com/announcements/introducing-the-parse-server-dashboard) - Added a sub-section on this in guide
- [x] Test [push notification instructions](http://guides.codepath.com/ios/Configuring-a-Parse-Server#enabling-push-notifications) - Added a section for this in guide
- [x] Show Data schema
- [x] Parse Architecture Diagram

**Comment by nickai** [comment]
@aamays - Just had a student ask about how to convert a PFFile to an image that can be displayed in their TableView. I think we should add a section on ParseUI and using PFImageView.

```swift
import UIKit
import Parse
import ParseUI

class InstagramPostTableViewCell: UITableViewCell {

    @IBOutlet weak var photoView: PFImageView!

    var instagramPost: PFObject! {
        didSet {
            self.photoView.file = instagramPost["image"] as? PFFile
            self.photoView.loadInBackground()
        }
    }
}
```

**Comment by rogerhu** [comment]
We need to vet Parse files..there is an adapter for Mongo called GridStore
and has some file size limitations....there is also an Amazon s3 adapter
that could be used too..

**Comment by nickai** [comment]
@aamays - Looks like there might be an [issue](https://github.com/ParsePlatform/parse-server/issues/697) with push notifications with Parse Server. (Thanks @rogerhu for the link!)

**Comment by nickai** [comment]
@aamays - Do you have some time to close out the remaining items for the Parse guide? A lot of the schools will be hitting the implementation phase of the group project soon so it will be great to have all the support materials in place.

**Comment by rogerhu** [comment]
FWIW -- Parse dashboard is still very raw, and has limited functionality (no push testing).  The mLab data viewer or Robomongo probably is sufficient to use.

**Comment by aamays** [comment]
Hi @nickai, 

Sure let me wrap it up this weekend.

Thanks!
Amay

**Comment by nickai** [comment]
:+1:
