### ISSUE TITLE
Port designer guides

### ISSUE THREAD

**Issue by timothy1ee** [codepath/ios_guides#5]
Move guides from [internal courses content](https://github.com/codepath/courses_content/tree/master/ios_for_designers/pages) to the wiki. There should be an categorized index that has all the designer guides.

**Comment by tonysherbondy** [comment]
OK... I think this one is done.  Take a look and let me know. I just made a very quick pass at hierarchical organization so let me know if there is a better way.

**Comment by timothy1ee** [comment]
Great, this is what I had in mind, thanks!
