### ISSUE TITLE
Button guide

### ISSUE THREAD

**Issue by timothy1ee** [codepath/ios_guides#6]
Guide should include how to configure a button.

- In Interface Builder, toggle states to configure image/title/background image.
- Configure title/image insets
- Register for the button action
- Toggle the selected state on click
- Disable a button

**Comment by tonysherbondy** [comment]
@timothy1ee this should be done now.

**Comment by MAN2027079** [comment]
HI for some reason I;m getting your emails. I not part of any coding
project.

On Tue, May 12, 2015 at 3:25 PM, Anthony Sherbondy <notifications@github.com
