### ISSUE TITLE
iOS Week 2 Lab

### ISSUE THREAD

**Issue by timothy1ee** [codepath/ios_guides#7]
Update the Week 2 lab [here](https://github.com/codepath/courses_content/blob/master/intro_to_ios/exercises/exercise_2.md)

**Comment by nickai** [comment]
@timothy1ee - I've taken a pass at this before. Was there anything in particular you want updated or should I close this out?

**Comment by nickai** [comment]
Closing this out. We can reopen on the courses_content repo if needed.
