### ISSUE TITLE
Review Assignment #2

### ISSUE THREAD

**Issue by timothy1ee** [codepath/ios_guides#8]
Clarify the second assignment.

- Update filter screenshot. I just added a screenshot of the real app, but that's deceptive because those filter options aren't available in the Yelp API. You can use this student implementation to create a better screenshot: https://github.com/swaroopbutala/yelpiOS
- Add a link to the [Yelp categories](https://gist.githubusercontent.com/timothy1ee/e23415fa468c76e84fb3/raw/d009d39629f3000cb40a01aed0626016c1fa19f3/gistfile1.swift).
- Create a use case guide for embedding the search bar in the navigation bar. I'm not sure what the right way to do this is, you might have to investigate. In the past, I've set the search bar as the titleView of the navigation bar. That works for simple styling, but it has some weird visual glitches when popping/pushing. I've also embedded the search bar in a uiview and set that to the titleView. That fixed the visual glitches, but it was unclear how to dimension the UIView properly.

**Comment by nickai** [comment]
Moving to courses_content repo.
