### ISSUE TITLE
Document unretweeting

### ISSUE THREAD

**Issue by timothy1ee** [codepath/ios_guides#9]
I'm not sure how to unretweet, but I know that many people struggle with it. I've been told the below is true. Can you test and write this up? This probably belongs in an internal page to the courses portal. Just add a .md file to the pages folder, and you can link to it from the assignments page.

   - 1. You always want to be sending the include_my_retweet param - this should make sure that you're getting back the user/self tweet rather than just the original tweet (i.e. someone else's tweet). (You should be able to pass this param for a single status as well)
   - 2. At Twitter, each status in our model had 2 IDs - one was just the status ID and the other was the representedStatusId - this way we would keep the info for both the original status and the RT status (if one existed, otherwise these values were the same).

**Comment by nickai** [comment]
Moving to the courses_content repo
